title: Data Science Portfolio
logo: /images/logo.png
description: Data Queen // Senior Analyst
show_downloads: True
theme: jekyll-theme-minimal
defaults:
  - scope:
      path: ""
    values:
      layout: default
sass:
  style: compressed
