title: Data Science Portfolio
logo: assets/logo.png
description: Data Queen // Senior Analyst
show_downloads: True
baseurl: "/Vegetable_TimeSeries"
theme: jekyll-theme-minimal
sidebar:
  enabled: true
